spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test666?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&autoReconnect=true&useSSL=false
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
